[package]
name = "htymlx"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
# rust-yaml = "0.0.5"
rust-yaml = { git = "https://github.com/lucas-campagna/rust-yaml.git" }
indexmap = { version = "2.0" }

