[package]
name = "ymx"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11.8" 
regex = "1.12.2"
rust-yaml = { git = "https://github.com/lucas-campagna/rust-yaml.git" }
indexmap = { version = "2.0" }
meval = "0.2"